# Generated by Django 3.1.2 on 2020-11-07 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
