# Generated by Django 3.1.2 on 2020-11-07 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_delete_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hint',
            field=models.CharField(default='ss', max_length=100),
            preserve_default=False,
        ),
    ]
