# Generated by Django 3.1.2 on 2020-11-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0004_team_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='password',
            new_name='passwords',
        ),
    ]
