# Generated by Django 3.1.2 on 2020-11-07 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_auto_20201107_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='passwords',
        ),
    ]
