# Generated by Django 3.1.2 on 2020-11-07 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20201001_1755'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='ss', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
