# Generated by Django 3.1.2 on 2020-11-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_auto_20201107_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.taskcategory'),
        ),
    ]
