# Generated by Django 3.1.2 on 2020-11-07 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_sprint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sprint',
            name='task',
        ),
        migrations.CreateModel(
            name='SprintTasks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sprint', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='task.sprint')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sprint_tasks', to='task.task')),
            ],
            options={
                'verbose_name': 'Sprint Task',
                'verbose_name_plural': 'Sprint Tasks',
            },
        ),
    ]
