# Generated by Django 3.1.2 on 2020-11-07 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_auto_20201107_1223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprinttasks',
            name='sprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.sprint'),
        ),
    ]
