# Generated by Django 3.1.2 on 2020-11-07 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0008_auto_20201107_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='sprint',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='task.sprint'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SprintTasks',
        ),
    ]
